// Cosmic Blueprint Academy — beginner-friendly course content.

export interface QuizQuestion { q: string; choices: string[]; answer: number; explain: string; }

export interface PlanetEntry {
  name: string; glyph: string; tagline: string;
  represents: string; traits: string; strengths: string; challenges: string;
  everyday: string; inReport: string;
}
export interface SignEntry {
  name: string; glyph: string; dates: string;
  element: "Fire" | "Earth" | "Air" | "Water";
  modality: "Cardinal" | "Fixed" | "Mutable";
  keywords: string; strengths: string; weaknesses: string; famous: string;
}
export interface HouseEntry {
  number: number; name: string; rules: string; questions: string; example: string; why: string;
}
export interface AspectEntry {
  name: string; glyph: string; angle: number; meaning: string;
  vibe: "harmony" | "tension" | "neutral"; example: string;
}

export const PLANETS: PlanetEntry[] = [
  { name: "Sun", glyph: "☉", tagline: "Your core identity",
    represents: "Your essential self — the 'I am' at the center of your personality.",
    traits: "Confidence, willpower, creative spark, vitality.",
    strengths: "Leadership, self-expression, sense of purpose.",
    challenges: "Ego, pride, needing recognition to feel whole.",
    everyday: "When you say 'this is who I am' — that's your Sun talking.",
    inReport: "Anchors the entire personality reading and life-purpose sections." },
  { name: "Moon", glyph: "☽", tagline: "Your emotional inner world",
    represents: "Feelings, instincts, the part of you that needs comfort and safety.",
    traits: "Mood, memory, nurture, intuition.",
    strengths: "Empathy, emotional intelligence, care for others.",
    challenges: "Mood swings, clinging to the past, emotional eating.",
    everyday: "How you self-soothe at 11pm — that's your Moon.",
    inReport: "Drives inner-child, attachment, and emotional-healing sections." },
  { name: "Mercury", glyph: "☿", tagline: "How you think and speak",
    represents: "Mind, communication, learning style, short trips, daily logic.",
    traits: "Curiosity, wit, language, analysis.",
    strengths: "Quick thinking, clear writing, problem-solving.",
    challenges: "Overthinking, gossip, mental restlessness.",
    everyday: "The way you text, argue, or explain something to a friend.",
    inReport: "Communication style, learning style, sibling/peer dynamics." },
  { name: "Venus", glyph: "♀", tagline: "Love, beauty, and what you value",
    represents: "Affection, taste, art, money, what feels pleasurable.",
    traits: "Charm, sensuality, harmony.",
    strengths: "Building connection, aesthetic sense, generosity.",
    challenges: "Vanity, indulgence, avoiding conflict.",
    everyday: "Why a song makes you cry, or who you swipe right on.",
    inReport: "Romance, attraction, money & values, creativity." },
  { name: "Mars", glyph: "♂", tagline: "Drive, anger, desire",
    represents: "Action, courage, sex drive, how you fight for what you want.",
    traits: "Energy, assertion, instinct.",
    strengths: "Initiative, bravery, stamina.",
    challenges: "Impulsiveness, aggression, burnout.",
    everyday: "The moment you finally stand up for yourself.",
    inReport: "Ambition, conflict style, libido, athletic energy." },
  { name: "Jupiter", glyph: "♃", tagline: "Growth, luck, meaning",
    represents: "Expansion, philosophy, travel, abundance, optimism.",
    traits: "Generosity, faith, exuberance.",
    strengths: "Vision, teaching, attracting opportunity.",
    challenges: "Overdoing it, preachiness, blind optimism.",
    everyday: "The unexpected yes that changes your year.",
    inReport: "Purpose, manifestation, education, beliefs." },
  { name: "Saturn", glyph: "♄", tagline: "Discipline, structure, time",
    represents: "Responsibility, limits, mastery through effort.",
    traits: "Patience, realism, ambition.",
    strengths: "Maturity, follow-through, building lasting things.",
    challenges: "Fear, rigidity, depression, harsh self-criticism.",
    everyday: "Saving for ten years to buy a home.",
    inReport: "Career, fears, life lessons, midlife passage." },
  { name: "Uranus", glyph: "♅", tagline: "Sudden change, originality",
    represents: "Innovation, rebellion, awakenings, freedom.",
    traits: "Inventiveness, eccentricity, electricity.",
    strengths: "Genius insights, breaking outdated patterns.",
    challenges: "Disruption, unreliability, alienation.",
    everyday: "Quitting the job in a single afternoon.",
    inReport: "Awakenings, breakthroughs, queer identity, tech genius." },
  { name: "Neptune", glyph: "♆", tagline: "Dreams, mysticism, illusion",
    represents: "Imagination, spirituality, compassion, the unconscious.",
    traits: "Sensitivity, art, transcendence.",
    strengths: "Empathy, vision, healing gifts.",
    challenges: "Confusion, escapism, addiction, deception.",
    everyday: "Losing track of time inside a song or a daydream.",
    inReport: "Psychic gifts, dreams, addiction patterns, spirituality." },
  { name: "Pluto", glyph: "♇", tagline: "Power, death, rebirth",
    represents: "Deep transformation, taboo, what we obsess over.",
    traits: "Intensity, depth, regeneration.",
    strengths: "Endurance, truth-seeing, alchemy of pain.",
    challenges: "Control, manipulation, obsession, paranoia.",
    everyday: "The moment you can't go back to who you were.",
    inReport: "Shadow work, trauma, sexual power, ancestral lineage." },
];

export const SIGNS: SignEntry[] = [
  { name: "Aries", glyph: "♈", dates: "Mar 21 – Apr 19", element: "Fire", modality: "Cardinal",
    keywords: "Pioneer, warrior, spark",
    strengths: "Brave, decisive, energetic.", weaknesses: "Impatient, impulsive, blunt.",
    famous: "Starts things others are afraid to start." },
  { name: "Taurus", glyph: "♉", dates: "Apr 20 – May 20", element: "Earth", modality: "Fixed",
    keywords: "Stable, sensual, grounded",
    strengths: "Patient, loyal, reliable.", weaknesses: "Stubborn, possessive, slow to change.",
    famous: "Builds beauty and security that lasts." },
  { name: "Gemini", glyph: "♊", dates: "May 21 – Jun 20", element: "Air", modality: "Mutable",
    keywords: "Curious, clever, social",
    strengths: "Witty, adaptable, communicative.", weaknesses: "Restless, scattered, gossipy.",
    famous: "Has a question for every answer." },
  { name: "Cancer", glyph: "♋", dates: "Jun 21 – Jul 22", element: "Water", modality: "Cardinal",
    keywords: "Nurturing, protective, sensitive",
    strengths: "Caring, intuitive, loyal.", weaknesses: "Moody, clingy, self-protective.",
    famous: "Creates a home wherever they go." },
  { name: "Leo", glyph: "♌", dates: "Jul 23 – Aug 22", element: "Fire", modality: "Fixed",
    keywords: "Radiant, generous, dramatic",
    strengths: "Warm, confident, creative.", weaknesses: "Proud, attention-hungry, dramatic.",
    famous: "Turns life into a stage worth showing up to." },
  { name: "Virgo", glyph: "♍", dates: "Aug 23 – Sep 22", element: "Earth", modality: "Mutable",
    keywords: "Analytical, useful, refined",
    strengths: "Precise, helpful, hardworking.", weaknesses: "Critical, anxious, perfectionist.",
    famous: "Fixes what nobody else noticed was broken." },
  { name: "Libra", glyph: "♎", dates: "Sep 23 – Oct 22", element: "Air", modality: "Cardinal",
    keywords: "Diplomatic, fair, aesthetic",
    strengths: "Charming, balanced, partnership-oriented.", weaknesses: "Indecisive, conflict-avoidant.",
    famous: "Weighs both sides until the truth shows up." },
  { name: "Scorpio", glyph: "♏", dates: "Oct 23 – Nov 21", element: "Water", modality: "Fixed",
    keywords: "Intense, magnetic, transformative",
    strengths: "Loyal, perceptive, courageous.", weaknesses: "Jealous, secretive, vengeful.",
    famous: "Sees through every mask." },
  { name: "Sagittarius", glyph: "♐", dates: "Nov 22 – Dec 21", element: "Fire", modality: "Mutable",
    keywords: "Adventurous, philosophical, free",
    strengths: "Optimistic, bold, truthful.", weaknesses: "Tactless, restless, preachy.",
    famous: "Books the one-way ticket." },
  { name: "Capricorn", glyph: "♑", dates: "Dec 22 – Jan 19", element: "Earth", modality: "Cardinal",
    keywords: "Ambitious, structured, enduring",
    strengths: "Disciplined, responsible, strategic.", weaknesses: "Cold, status-driven, pessimistic.",
    famous: "Climbs the mountain everyone else gave up on." },
  { name: "Aquarius", glyph: "♒", dates: "Jan 20 – Feb 18", element: "Air", modality: "Fixed",
    keywords: "Visionary, humanitarian, unconventional",
    strengths: "Inventive, independent, progressive.", weaknesses: "Detached, contrarian, aloof.",
    famous: "Imagines the future the rest of us live in." },
  { name: "Pisces", glyph: "♓", dates: "Feb 19 – Mar 20", element: "Water", modality: "Mutable",
    keywords: "Mystical, compassionate, dreamy",
    strengths: "Empathetic, artistic, spiritual.", weaknesses: "Escapist, foggy, easily overwhelmed.",
    famous: "Feels what no one else admits to feeling." },
];

export const HOUSES: HouseEntry[] = [
  { number: 1, name: "House of Self", rules: "Identity, body, first impressions, the mask you wear out.",
    questions: "Who am I? How do people see me?", example: "Your style, your face, the energy you give off.",
    why: "Any planet here colors your whole vibe." },
  { number: 2, name: "House of Value", rules: "Money, possessions, self-worth, what you build.",
    questions: "What do I value? How do I earn?", example: "Your bank account, your skills, your taste.",
    why: "Planets here shape your relationship with money." },
  { number: 3, name: "House of Mind", rules: "Communication, siblings, learning, short trips.",
    questions: "How do I think and connect?", example: "Texts, school, your relationship with your sister.",
    why: "Planets here run your daily mental world." },
  { number: 4, name: "House of Home", rules: "Roots, family, mother, ancestral patterns, where you feel safe.",
    questions: "Where do I come from?", example: "Childhood bedroom memories, your current kitchen.",
    why: "Planets here run your deepest emotional ground." },
  { number: 5, name: "House of Pleasure", rules: "Romance, creativity, children, play, self-expression.",
    questions: "How do I have fun and create?", example: "Flirting, painting, your kids, your hobbies.",
    why: "Planets here glow when you're being authentically you." },
  { number: 6, name: "House of Service", rules: "Work routines, health, pets, daily habits.",
    questions: "How do I take care of body and tasks?", example: "Your gym routine, your inbox, your dog.",
    why: "Planets here run the texture of your daily life." },
  { number: 7, name: "House of Partnership", rules: "Marriage, business partners, open enemies.",
    questions: "Who do I mirror with?", example: "Your spouse, your therapist, your nemesis.",
    why: "Planets here describe the people you keep attracting." },
  { number: 8, name: "House of Transformation", rules: "Sex, death, shared resources, deep merging.",
    questions: "Where do I lose and rebuild myself?", example: "Therapy, inheritance, intimacy.",
    why: "Planets here mark your zones of rebirth." },
  { number: 9, name: "House of Meaning", rules: "Travel, higher learning, philosophy, publishing.",
    questions: "What do I believe?", example: "Grad school, your spiritual path, that month in Bali.",
    why: "Planets here expand how you make meaning." },
  { number: 10, name: "House of Career", rules: "Public reputation, vocation, father, legacy.",
    questions: "What am I known for?", example: "Your job title, your LinkedIn, what people say about you.",
    why: "Planets here build your public image." },
  { number: 11, name: "House of Community", rules: "Friends, networks, causes, hopes, the long future.",
    questions: "Who is my tribe?", example: "Group chats, activism, your big dream.",
    why: "Planets here describe how you belong." },
  { number: 12, name: "House of the Unseen", rules: "Subconscious, dreams, hidden enemies, spirituality, what you can't see.",
    questions: "What lives behind the curtain?", example: "Therapy, meditation, the patterns you keep repeating.",
    why: "Planets here work quietly but powerfully." },
];

export const ASPECTS: AspectEntry[] = [
  { name: "Conjunction", glyph: "☌", angle: 0, meaning: "Two energies fused — they act as one for better or worse.",
    vibe: "neutral", example: "Sun ☌ Mercury: your identity and your voice are the same thing." },
  { name: "Opposition", glyph: "☍", angle: 180, meaning: "A see-saw — two needs that pull against each other until you balance them.",
    vibe: "tension", example: "Moon ☍ Saturn: feelings vs. duty. Learn to hold both." },
  { name: "Square", glyph: "□", angle: 90, meaning: "Friction that forces growth — the muscle you build by doing hard reps.",
    vibe: "tension", example: "Mars □ Pluto: anger meets power. Forged, not gifted." },
  { name: "Trine", glyph: "△", angle: 120, meaning: "Easy flow — a natural talent you might take for granted.",
    vibe: "harmony", example: "Venus △ Jupiter: charm and luck arrive together." },
  { name: "Sextile", glyph: "✱", angle: 60, meaning: "An open door — opportunity you have to walk through on purpose.",
    vibe: "harmony", example: "Mercury ✱ Uranus: brilliant ideas, if you act on them." },
  { name: "Quincunx", glyph: "⚻", angle: 150, meaning: "An awkward gear-shift — two parts that don't naturally speak, requiring constant adjustment.",
    vibe: "tension", example: "Sun ⚻ Moon: who you are and what you feel keep needing to be reconciled." },
];

export interface LessonMeta { id: string; number: number; title: string; tagline: string; minutes: number; }
export const LESSONS: LessonMeta[] = [
  { id: "what-is-natal", number: 1, title: "What Is a Natal Chart?", tagline: "A snapshot of the sky the moment you were born.", minutes: 5 },
  { id: "planets", number: 2, title: "The Planets", tagline: "Ten cosmic characters that live inside you.", minutes: 12 },
  { id: "signs", number: 3, title: "The Zodiac Signs", tagline: "Twelve flavors each planet can wear.", minutes: 12 },
  { id: "houses", number: 4, title: "The 12 Houses", tagline: "Where in your life the action happens.", minutes: 10 },
  { id: "combinations", number: 5, title: "Planet + Sign + House", tagline: "How interpretations are actually built.", minutes: 6 },
  { id: "aspects", number: 6, title: "Aspects", tagline: "How planets talk to each other.", minutes: 8 },
  { id: "angles", number: 7, title: "Ascendant & Midheaven", tagline: "Your mask and your mission.", minutes: 6 },
  { id: "special", number: 8, title: "Special Points", tagline: "Nodes, Chiron, Lilith, Fortune, Vertex.", minutes: 7 },
  { id: "putting-together", number: 9, title: "Putting It All Together", tagline: "Walk through a real chart, placement by placement.", minutes: 9 },
  { id: "reading-reports", number: 10, title: "Reading Your Cosmic Blueprint Report", tagline: "Translate symbols into self-knowledge.", minutes: 6 },
];

export const QUIZZES: Record<string, QuizQuestion[]> = {
  "what-is-natal": [
    { q: "What is a natal chart?", choices: ["A horoscope for today", "A snapshot of the sky at your exact birth moment", "A prediction of your death"], answer: 1, explain: "It maps where every planet was the instant you were born." },
    { q: "Why does birth time matter so much?", choices: ["It doesn't, only the date matters", "It determines the Ascendant and house placements, which shift every 4 minutes", "It only changes your Moon sign"], answer: 1, explain: "The Ascendant moves about one degree every four minutes." },
    { q: "What's the difference between astrology and astronomy?", choices: ["Nothing", "Astronomy measures the sky; astrology interprets meaning from it", "Astrology is older and more scientific"], answer: 1, explain: "Astronomy is science; astrology is a symbolic language built on top." },
    { q: "Why does birth location matter?", choices: ["Stars look different from different places", "Houses are calculated using your latitude and longitude", "It changes your Sun sign"], answer: 1, explain: "Houses depend on which part of the sky was overhead at your location." },
    { q: "Cosmic Blueprint uses which zodiac system?", choices: ["Sidereal (Vedic)", "Tropical (Western)", "Chinese"], answer: 1, explain: "Tropical zodiac with Placidus houses — the Western standard." },
  ],
  "planets": [
    { q: "Which planet represents your emotional inner world?", choices: ["Sun", "Moon", "Mars"], answer: 1, explain: "The Moon governs feelings and what makes you feel safe." },
    { q: "Venus rules…", choices: ["Anger and drive", "Love, beauty, and values", "Career"], answer: 1, explain: "Venus is affection, taste, and what you find pleasurable." },
    { q: "Saturn is the planet of…", choices: ["Discipline and limits", "Sudden change", "Dreams"], answer: 0, explain: "Saturn teaches through structure, time, and earned mastery." },
    { q: "Pluto is associated with…", choices: ["Quick communication", "Death, rebirth, and deep power", "Wealth and luck"], answer: 1, explain: "Pluto rules transformation and taboo." },
    { q: "Mercury governs…", choices: ["Thinking and communication", "Love", "Athletic strength"], answer: 0, explain: "Mercury is the mind: language and daily logic." },
    { q: "Which planet rules expansion, optimism, and luck?", choices: ["Mars", "Jupiter", "Neptune"], answer: 1, explain: "Jupiter is the cosmic 'yes' — growth and abundance." },
  ],
  "signs": [
    { q: "How many zodiac signs are there?", choices: ["10", "12", "13"], answer: 1, explain: "Twelve 30° slices of the ecliptic." },
    { q: "Which element is Scorpio?", choices: ["Fire", "Water", "Earth"], answer: 1, explain: "Scorpio is fixed water — deep and intense." },
    { q: "Cardinal signs are…", choices: ["Initiators", "Stabilizers", "Adapters"], answer: 0, explain: "Aries, Cancer, Libra, Capricorn — they start things." },
    { q: "Fixed signs are…", choices: ["Initiators", "Stabilizers", "Adapters"], answer: 1, explain: "Taurus, Leo, Scorpio, Aquarius — they hold and sustain." },
    { q: "Which sign is known as the diplomat?", choices: ["Libra", "Aries", "Pisces"], answer: 0, explain: "Libra weighs both sides until balance is found." },
  ],
  "houses": [
    { q: "The 1st house is about…", choices: ["Money", "Identity and first impressions", "Career"], answer: 1, explain: "It's the rising self — body, mask, vibe." },
    { q: "Which house rules career and public reputation?", choices: ["4th", "7th", "10th"], answer: 2, explain: "The 10th is your public image and vocation." },
    { q: "The 7th house is about…", choices: ["Solitude", "Partnerships and mirrors", "Travel"], answer: 1, explain: "Marriage, business partners, even open enemies." },
    { q: "Which house rules deep transformation and shared resources?", choices: ["5th", "8th", "11th"], answer: 1, explain: "The 8th — rebirth and intimate merging." },
    { q: "The 12th house is associated with…", choices: ["Money", "The subconscious and hidden things", "Children"], answer: 1, explain: "Dreams, spirituality, what works behind the curtain." },
  ],
  "combinations": [
    { q: "How are placements built?", choices: ["Planet only", "Planet + Sign + House", "Just the sign"], answer: 1, explain: "What (planet), how (sign), and where (house)." },
    { q: "'Moon in Pisces in the 4th House' tells you about…", choices: ["Career", "Emotional life at home and roots", "Finances"], answer: 1, explain: "Moon = emotions, Pisces = dreamy, 4th = home." },
    { q: "Venus in Leo in the 5th House makes love…", choices: ["Secretive and quiet", "Dramatic, generous, playful", "Strictly about money"], answer: 1, explain: "Venus + Leo + 5th = romance with flair." },
    { q: "Mars in Capricorn in the 10th House drives you toward…", choices: ["Hiding", "Disciplined career ambition", "Travel"], answer: 1, explain: "Mars + Capricorn + 10th = ambitious work." },
  ],
  "aspects": [
    { q: "A conjunction is two planets…", choices: ["Far apart", "Right on top of each other", "On opposite sides"], answer: 1, explain: "0° apart — energies fuse." },
    { q: "Which aspect is the most harmonious?", choices: ["Square", "Trine", "Opposition"], answer: 1, explain: "Trines (120°) feel like easy flow." },
    { q: "A square aspect creates…", choices: ["Effortless harmony", "Friction that forces growth", "Pure luck"], answer: 1, explain: "Squares are tension that builds strength." },
    { q: "Oppositions teach you to…", choices: ["Pick a side", "Balance two opposite needs", "Ignore one planet"], answer: 1, explain: "180° is a see-saw — integration is the work." },
    { q: "A sextile is best described as…", choices: ["A demand", "An open door requiring action", "An accident"], answer: 1, explain: "60° — opportunity you walk through." },
  ],
  "angles": [
    { q: "Your Rising Sign describes…", choices: ["Soul purpose", "The mask and first impressions", "Career"], answer: 1, explain: "It's the sign rising at your birth — your social skin." },
    { q: "The Midheaven shows…", choices: ["Hidden self", "Public reputation and life direction", "Love life"], answer: 1, explain: "The highest point — what you're known for." },
    { q: "The Descendant is opposite…", choices: ["The Midheaven", "The Ascendant", "The Sun"], answer: 1, explain: "It describes the partner-mirror." },
    { q: "The IC represents…", choices: ["Career", "Roots, ancestry, deepest home", "Friends"], answer: 1, explain: "Bottom of the chart — private foundation." },
  ],
  "special": [
    { q: "The North Node is…", choices: ["Where you came from", "Your growth edge this lifetime", "A planet"], answer: 1, explain: "Qualities your soul is here to develop." },
    { q: "Chiron is the…", choices: ["Lucky asteroid", "Wounded healer", "Warrior"], answer: 1, explain: "A wound that becomes medicine." },
    { q: "Black Moon Lilith represents…", choices: ["Childhood", "The wild feminine and what gets shamed", "Marriage"], answer: 1, explain: "Raw, unapologetic power." },
    { q: "Part of Fortune indicates…", choices: ["Where joy flows naturally", "Your debts", "Your enemies"], answer: 0, explain: "Asc + Moon − Sun — where things click." },
    { q: "The Vertex is associated with…", choices: ["Fated meetings", "Daily routines", "Health"], answer: 0, explain: "Pivotal encounters and turning points." },
  ],
  "putting-together": [
    { q: "A full interpretation weaves…", choices: ["Only the Sun sign", "Planets, signs, houses, aspects, angles", "Just the rising sign"], answer: 1, explain: "Every layer modifies the others." },
    { q: "Sun in Scorpio in the 8th conjunct Pluto suggests…", choices: ["Light and breezy", "Intense transformation and depth", "Career only"], answer: 1, explain: "All three signal deep rebirth." },
    { q: "Two contradictory placements mean…", choices: ["The chart is wrong", "You hold both — humans are layered", "Ignore one"], answer: 1, explain: "Charts are tapestries, not single notes." },
  ],
  "reading-reports": [
    { q: "A placement like 'Venus in Leo in the 5th' reads as…", choices: ["Skim it", "Planet + flavor + life area", "Sign only"], answer: 1, explain: "That's how interpretations are constructed." },
    { q: "If two sections seem to contradict…", choices: ["Report is broken", "You hold both truths", "Trust only the first"], answer: 1, explain: "Real charts include tension." },
    { q: "An aspect like 'Moon square Saturn' means…", choices: ["Ignore it", "Notice the friction and work with it", "Try to remove it"], answer: 1, explain: "Aspects are inner conversations." },
    { q: "Reports are best used as…", choices: ["Hard prophecy", "A mirror for self-reflection", "Medical advice"], answer: 1, explain: "Astrology describes potentials, not outcomes." },
  ],
};

export interface GlossaryTerm { term: string; def: string; }
export const GLOSSARY: GlossaryTerm[] = [
  { term: "Natal Chart", def: "A map of the sky at the exact moment and place of your birth." },
  { term: "Ascendant (Rising)", def: "The zodiac sign rising on the eastern horizon at your birth. Your social mask." },
  { term: "Midheaven (MC)", def: "The highest point of the chart. Public reputation, career, life direction." },
  { term: "Descendant", def: "Opposite the Ascendant. Qualities you seek in partners." },
  { term: "IC", def: "Imum Coeli — the bottom of the chart. Roots, ancestry, home." },
  { term: "House", def: "One of 12 slices of life experience the chart is divided into." },
  { term: "Cusp", def: "The starting line of a house." },
  { term: "Conjunction", def: "Two planets within ~8° of each other. Energies fuse." },
  { term: "Opposition", def: "Planets ~180° apart. A see-saw needing balance." },
  { term: "Square", def: "Planets ~90° apart. Friction that builds strength." },
  { term: "Trine", def: "Planets ~120° apart. Easy flow, natural talent." },
  { term: "Sextile", def: "Planets ~60° apart. Opportunity, with effort." },
  { term: "Quincunx", def: "Planets ~150° apart. Awkward adjustment." },
  { term: "Orb", def: "How exact an aspect is. Tighter orb = stronger aspect." },
  { term: "Retrograde", def: "A planet appearing to move backward from Earth's view. Themes turn inward." },
  { term: "North Node", def: "Your growth edge — what your soul is here to learn." },
  { term: "South Node", def: "Familiar territory from the past — easy but limiting." },
  { term: "Chiron", def: "The wounded healer — a wound that becomes your medicine." },
  { term: "Black Moon Lilith", def: "The wild, unapologetic feminine. What gets shamed but won't be tamed." },
  { term: "Part of Fortune", def: "A calculated point of joy and ease (Asc + Moon − Sun)." },
  { term: "Vertex", def: "A 'fate point' associated with pivotal encounters." },
  { term: "Placidus", def: "The most common house system in Western astrology." },
  { term: "Tropical Zodiac", def: "The Western system, tied to the seasons." },
  { term: "Element", def: "Fire, Earth, Air, or Water — the basic energy of a sign." },
  { term: "Modality", def: "Cardinal (starter), Fixed (sustainer), Mutable (adapter)." },
  { term: "Applying", def: "An aspect getting tighter — its energy is building." },
  { term: "Separating", def: "An aspect loosening — its energy is releasing." },
  { term: "Aspect", def: "An angular relationship between two planets." },
  { term: "Glyph", def: "The symbol used for a planet, sign, or aspect (e.g., ☉ for Sun)." },
  { term: "Ephemeris", def: "A table of planetary positions. Cosmic Blueprint uses Swiss Ephemeris." },
];