import type { ReportDefinition } from "./reports-catalog-base";

/**
 * Premium Synastry Series — 10 new two-chart relationship reports.
 * Each requires a partner chart (requiresPartner: true).
 * Powered by the deterministic synastry engine (cross-aspects + house overlays + domain scores).
 */
export const SYNASTRY_SERIES_REPORTS: ReportDefinition[] = [
  {
    id: "synastry-classic-compatibility",
    title: "Classic Synastry Compatibility",
    tagline: "The complete two-chart relationship blueprint — attraction, friction, and long-term potential.",
    icon: "⚯",
    category: "Relationships",
    requiresPartner: true,
    targetWords: 2800,
    estimatedPages: 32,
    readingMinutes: 45,
    sections: [
      "How to Read This Synastry Report",
      "Natal Snapshot — Person A",
      "Natal Snapshot — Person B",
      "Overall Compatibility Scorecard",
      "Sun–Moon & Core Identity Dynamics",
      "Venus–Mars Chemistry & Desire",
      "Mercury Communication Patterns",
      "Emotional Safety (Moon & 4th House Overlays)",
      "Partnership Style (7th House Overlays)",
      "Intimacy & Trust (8th House & Pluto)",
      "Growth & Expansion (Jupiter Contacts)",
      "Structure, Commitment & Tests (Saturn)",
      "Uranus, Neptune & Pluto — The Outer Forces",
      "House Overlays That Matter Most",
      "Key Strengths of This Pairing",
      "Key Friction Points & How to Navigate Them",
      "Repair Potential & Conflict Style",
      "Long-Term Partnership Outlook",
      "Practical Agreements Drawn From the Charts",
      "Closing Reflection",
    ],
    systemFraming:
      "Write a professional, psychologically sophisticated synastry interpretation for two real people. Use ONLY the calculated cross-aspects, house overlays, and domain scores provided. Name specific mutual aspects and overlays. Distinguish Person A and Person B clearly. Never invent placements or future events. Tone: warm, clear, non-fatalistic, practical.",
  },
  {
    id: "synastry-romantic-deep-dive",
    title: "Romantic Synastry Deep Dive",
    tagline: "Desire, attachment, romance language, and the emotional weather between you.",
    icon: "♡",
    category: "Relationships",
    requiresPartner: true,
    targetWords: 2600,
    estimatedPages: 30,
    readingMinutes: 42,
    sections: [
      "Opening: The Romantic Field Between You",
      "Natal Snapshot — You",
      "Natal Snapshot — Partner",
      "Attraction Signature (Venus–Mars–Ascendant)",
      "Emotional Attachment Style (Moon Contacts)",
      "Romance & Play (5th House Overlays)",
      "Committed Partnership Style (7th House)",
      "Desire & Sexual Charge (Mars–Pluto–Lilith)",
      "Idealization vs. Reality (Neptune Contacts)",
      "Where You Feel Safest Together",
      "Where You Feel Most Exposed",
      "Love Languages Written in the Charts",
      "Jealousy, Possession & Insecurity Patterns",
      "The Romance Cycle: Pursue, Merge, Withdraw",
      "What Keeps the Spark Alive",
      "What Quietly Erodes Romance",
      "A Shared Romance Operating System",
      "Closing: What Love Asks of You Both",
    ],
    systemFraming:
      "Intimate, psychologically precise romantic synastry. Center Venus, Mars, Moon, 5th/7th/8th house overlays and related cross-aspects. Distinguish fantasy from workable chemistry. Practical guidance only — no fate claims.",
  },
  {
    id: "synastry-friendship-circle",
    title: "Friendship & Chosen Family Synastry",
    tagline: "How you show up for each other as friends, allies, and chosen family.",
    icon: "☍",
    category: "Relationships",
    requiresPartner: true,
    targetWords: 2200,
    estimatedPages: 26,
    readingMinutes: 35,
    sections: [
      "Why This Friendship Matters",
      "Natal Snapshot — Person A",
      "Natal Snapshot — Person B",
      "Friendship Chemistry (Mercury–Jupiter–11th)",
      "Shared Values & Humor",
      "How You Support Each Other Under Stress",
      "Where Misunderstandings Arise",
      "Loyalty, Reliability & Trust Patterns",
      "Group Dynamics & Social Roles",
      "When Friendship Feels Easy",
      "When Friendship Feels Heavy",
      "Boundaries That Protect the Bond",
      "Growth You Offer Each Other",
      "A Simple Friendship Agreement",
      "Closing Reflection",
    ],
    systemFraming:
      "Warm, clear friendship synastry. Emphasize Mercury, Jupiter, 11th house overlays, Sun–Moon mutual respect, and communication aspects. Practical and affirming without being saccharine.",
  },
  {
    id: "synastry-business-partners",
    title: "Business Partnership Synastry",
    tagline: "How two charts negotiate, share risk, lead, and build together.",
    icon: "⚖",
    category: "Vocation",
    requiresPartner: true,
    targetWords: 2500,
    estimatedPages: 28,
    readingMinutes: 40,
    sections: [
      "Executive Summary of the Partnership",
      "Natal Snapshot — Partner A",
      "Natal Snapshot — Partner B",
      "Vision Alignment (Sun–Jupiter–MC)",
      "Execution Styles (Mars–Saturn–6th)",
      "Money, Equity & Risk Sharing (2nd/8th)",
      "Negotiation & Contract Patterns (Mercury–Venus–7th)",
      "Public Face & Brand (10th House Overlays)",
      "Conflict & Decision-Making Under Pressure",
      "Power Dynamics & Authority",
      "Where You Amplify Each Other",
      "Where You Frictionally Cancel Each Other",
      "Operating Cadence That Fits Both Charts",
      "Red Flags & Green Flags",
      "A Partnership Operating Agreement",
      "Closing: How to Build Sustainably",
    ],
    systemFraming:
      "Executive, pragmatic business synastry. Speak to founders and operators. Frame compatibility as workable design, not fate. Concrete recommendations drawn from exact cross-aspects and overlays.",
  },
  {
    id: "synastry-parent-child",
    title: "Parent–Child Synastry",
    tagline: "The emotional blueprint between parent and child — needs, triggers, and growth.",
    icon: "⌂",
    category: "Relationships",
    requiresPartner: true,
    targetWords: 2400,
    estimatedPages: 28,
    readingMinutes: 38,
    sections: [
      "A Compassionate Frame for This Reading",
      "Natal Snapshot — Parent",
      "Natal Snapshot — Child",
      "Core Emotional Climate (Moon Contacts)",
      "Authority, Structure & Boundaries (Saturn)",
      "Nurturing Style & Needs (4th House Overlays)",
      "Where the Child Feels Seen",
      "Where the Child Feels Misunderstood",
      "Triggers & Defensive Patterns",
      "Communication Across Generations",
      "Independence vs. Closeness",
      "Healing Opportunities in the Dynamic",
      "Practical Parenting Adjustments",
      "What the Child Needs Most From This Parent",
      "Closing Letter to Both",
    ],
    systemFraming:
      "Compassionate, non-blaming parent–child synastry. Never pathologize either person. Focus on needs, triggers, and growth. Use Moon, Saturn, 4th house overlays and related aspects. Supportive, clear language.",
  },
  {
    id: "synastry-twin-flame",
    title: "Twin Flame Synastry",
    tagline: "Mirror dynamics, intensity, separation themes, and sovereignty within the connection.",
    icon: "∞",
    category: "Relationships",
    requiresPartner: true,
    targetWords: 2600,
    estimatedPages: 30,
    readingMinutes: 42,
    sections: [
      "A Grounded Frame for Twin-Flame Language",
      "Natal Snapshot — Person A",
      "Natal Snapshot — Person B",
      "Mirror Signatures in the Charts",
      "Intensity & Merging (Pluto–8th House)",
      "Idealization & Longing (Neptune–12th)",
      "Nodal Contacts & Karmic Weight",
      "The Separation Stage — What It Serves",
      "The Reunion Stage — What Must Change",
      "Power, Obsession & Projection",
      "Where Sovereignty Is Tested",
      "What This Connection Activates in Each",
      "Healthy vs. Unhealthy Intensity",
      "Practices for Staying Centered",
      "When to Lean In / When to Create Space",
      "Closing: The Real Work of the Mirror",
    ],
    systemFraming:
      "Sober, discerning twin-flame synastry. Neither dismiss nor romanticize the framing. Center sovereignty, reality-testing, and growth. Use Pluto, Neptune, Nodes, 8th/12th overlays. Compassionate but clear-eyed.",
  },
  {
    id: "synastry-soulmate",
    title: "Soulmate Synastry",
    tagline: "Recognition, deep resonance, and the long arc of partnership potential.",
    icon: "✧",
    category: "Relationships",
    requiresPartner: true,
    targetWords: 2500,
    estimatedPages: 29,
    readingMinutes: 40,
    sections: [
      "What 'Soulmate' Means in This Reading",
      "Natal Snapshot — You",
      "Natal Snapshot — Partner",
      "Recognition Signatures (Sun–Moon–Nodes)",
      "Emotional Homecoming (Moon–Venus)",
      "Shared Purpose & Values",
      "Where You Complete Each Other",
      "Where You Challenge Each Other to Grow",
      "Commitment & Longevity Indicators (Saturn)",
      "Intimacy Depth (8th House Overlays)",
      "Communication as Sacred Practice",
      "The Shadow Side of Deep Bonding",
      "How This Connection Supports Soul Growth",
      "Practical Ways to Honor the Bond",
      "Closing Blessing",
    ],
    systemFraming:
      "Warm, reverent, yet grounded soulmate synastry. Avoid fate-language. Emphasize recognition, mutual growth, and workable partnership. Nodes, Moon, Venus, Saturn, 7th/8th overlays are central.",
  },
  {
    id: "synastry-sexual-chemistry",
    title: "Sexual Chemistry Synastry",
    tagline: "Erotic charge, desire styles, and the body-level conversation between two charts.",
    icon: "♂♀",
    category: "Intimacy (18+)",
    adult: true,
    requiresPartner: true,
    targetWords: 2400,
    estimatedPages: 28,
    readingMinutes: 38,
    sections: [
      "Consent & Framing Note",
      "Natal Snapshot — Person A",
      "Natal Snapshot — Person B",
      "Primary Erotic Signature (Mars–Venus–Pluto)",
      "Desire Style Differences",
      "Physical Chemistry Indicators",
      "Emotional Safety in Intimacy",
      "Power, Intensity & Surrender Themes",
      "Where Desire Aligns Easily",
      "Where Desire Collides or Misfires",
      "Fantasy vs. Embodied Connection",
      "Aftercare & Repair Patterns",
      "Keeping Chemistry Alive Over Time",
      "Boundaries That Protect Pleasure",
      "A Shared Erotic Map",
      "Closing: Conscious Desire",
    ],
    systemFraming:
      "Explicit, mature, consent-forward sexual synastry. Frame chemistry as workable patterns, not compulsion or fate. Use Mars, Venus, Pluto, Lilith, 5th/8th house overlays. Body-positive, inclusive, non-judgmental.",
  },
  {
    id: "synastry-long-term-partnership",
    title: "Long-Term Partnership Synastry",
    tagline: "Building a life together — commitment, daily rhythm, conflict repair, and shared future.",
    icon: "⚭",
    category: "Relationships",
    requiresPartner: true,
    targetWords: 2700,
    estimatedPages: 31,
    readingMinutes: 44,
    sections: [
      "The Long Arc of This Partnership",
      "Natal Snapshot — Partner A",
      "Natal Snapshot — Partner B",
      "Commitment Signatures (Saturn–7th)",
      "Daily Life Compatibility (6th House & Moon)",
      "Shared Values & Life Direction",
      "Money & Resource Sharing",
      "Home & Family Themes (4th House)",
      "Conflict Style & Repair Capacity",
      "Intimacy Maintenance Over Years",
      "Individual Autonomy Within the Bond",
      "Growth Edges for Each Partner",
      "What Sustains You Through Hard Seasons",
      "Practical Partnership Architecture",
      "A Living Agreement for the Years Ahead",
      "Closing: The Work of Staying",
    ],
    systemFraming:
      "Mature, practical long-term partnership synastry. Emphasize Saturn, 7th/4th/6th house overlays, Moon, Venus, and repair aspects. Concrete, sustainable guidance. No fairy-tale promises.",
  },
  {
    id: "synastry-family-dynamics",
    title: "Family Dynamics Synastry",
    tagline: "Multi-person family patterns — roles, alliances, tensions, and healing opportunities.",
    icon: "☷",
    category: "Relationships",
    requiresPartner: true,
    targetWords: 2300,
    estimatedPages: 27,
    readingMinutes: 36,
    sections: [
      "How to Use This Family Reading",
      "Natal Snapshot — Primary Person",
      "Natal Snapshot — Family Member",
      "Core Family Emotional Climate",
      "Roles You Naturally Take",
      "Roles They Naturally Take",
      "Alliance & Loyalty Patterns",
      "Tension & Trigger Points",
      "Communication Across the Family System",
      "Boundaries That Protect Everyone",
      "Healing Opportunities Between You",
      "What Each Person Needs From the Other",
      "Practical Family Agreements",
      "Closing: Repairing the Family Field",
    ],
    systemFraming:
      "Compassionate family-system synastry for two members. Non-blaming. Focus on roles, needs, triggers, and repair. Moon, Saturn, 4th house overlays and related aspects. Supportive, clear language suitable for adult family members.",
  },
];
