import type { ReportDefinition } from "./reports-catalog-base";

/**
 * UNFILTERED SERIES™ — 18 radically candid, 31-chapter flagship readings.
 * 11 natal + 2 flagship natal, 7 synastry (requiresPartner).
 * Every report: 31 chapters, ~5,000 words, $99, adult: false.
 */

export const UNFILTERED_SERIES_CATEGORY = "Unfiltered Series" as const;
export const UNFILTERED_SERIES_PRICE_CENTS = 9900;
export const UNFILTERED_SERIES_TARGET_WORDS = 5000;

export const UNFILTERED_CLOSING_SENTENCE =
  "Your chart does not give you an excuse. It gives you a mirror.";

const STANDARD = `UNFILTERED SERIES STANDARD (STRICT — the most demanding tier in the library).

VOICE: intimate, confrontational, intelligent, specific, psychologically observant, emotionally intense, occasionally uncomfortable, compassionate without going soft, challenging without cruelty. Never flatter. Never pad. Never write a sentence that could apply to anyone.

EVIDENCE: every significant interpretation — especially every difficult one — must name the actual calculated chart factor it reads (planet, sign, degree, house, aspect, ruler, node, Chiron, Lilith, Part of Fortune, Vertex, angularity, element/modality balance, and for two-chart reports the mutual aspect or house overlay). Never invent placements, aspects, houses, degrees, birth data, events, trauma, diagnoses, crimes, relationship history, motives, memories, secret thoughts or future events.

SEVEN-STEP METHOD for every major difficult pattern: (1) identify the signature, (2) explain the traditional symbolism, (3) show the healthy expression, (4) expose the shadow expression, (5) show the consequences for relationships, communication, ambition, intimacy, conflict, self-image, decision-making, trust or boundaries, (6) ask the uncomfortable question the reader cannot easily dismiss, (7) show the mature path.

CONTRADICTION ENGINE: actively hunt contradictory signatures the chart genuinely supports — independence vs. attachment, sensitivity vs. defensiveness, control vs. resistance to control, confidence vs. insecurity, intimacy hunger vs. intimacy avoidance, ambition vs. resistance to structure, recognition vs. discomfort with exposure, directness vs. indirect emotional expression. Present them as tensions, never as diagnoses.

EMOTIONAL PROGRESSION per chapter: worst-nightmare honesty → the astrological receipts → the mirror (how it shows up in real behavior) → the contradiction → the difficult question → the best-friend guidance → the power available when the same energy is integrated. Never leave the reader only with shame.

REQUIRED LANGUAGE: "this may suggest", "this pattern can manifest as", "under pressure this may become", "the shadow expression can look like", "others may experience this as", "the mature expression is".

FORBIDDEN: any claim that the reader is a narcissist, abusive, dangerous, mentally ill, traumatised, destined to suffer, certain to cheat or certain to break up; any statement of what another person secretly thinks, intends or feels; any prediction stated as fact; astrology framed as medical, psychiatric, legal or scientific diagnosis.

FORMAT: markdown. Each chapter opens with an italic "Chart Anchors" line listing the exact factors that chapter interprets, then the prose. No emojis. Do not restate the chart data as a list; weave it into interpretation.`;

const ENDING = `ENDING STANDARD: the penultimate chapter delivers exactly five numbered Brutal Truths — each specific to this chart, uncomfortable, evidence-based, non-diagnostic, and carrying a path toward growth. The final chapter is the transformational close: what pattern must stop being excused, what strength must stop being misused, what truth must be accepted, what choice can be made now, and what maturity looks like. The final chapter must end with exactly this sentence on its own line: "${UNFILTERED_CLOSING_SENTENCE}"`;

const NATAL_FRAMING = (premise: string) =>
  `UNFILTERED SERIES / NATAL. ${premise}\n\n${STANDARD}\n\n${ENDING}`;

const SYNASTRY_FRAMING = (premise: string) =>
  `UNFILTERED SERIES / SYNASTRY. ${premise}

TWO-CHART RULES: you are given Person A's natal chart, Person B's natal chart, the mutual (cross-chart) aspects, the A→B house overlays (Person A's planets placed in Person B's houses) and the B→A house overlays (Person B's planets placed in Person A's houses). Never reverse the overlay ownership, and never cite an overlay or mutual aspect that is not in the supplied data. Examine both people symmetrically; never assign blame from astrology and never state what either person secretly thinks, wants or intends. Treat attraction, familiarity, "karmic" or "fated" symbolism as interpretive symbolism only — never as proof of destiny, permanence, betrayal, abuse, reunion or inevitable breakup.

${STANDARD}

${ENDING}`;

interface Spec {
  id: string;
  title: string;
  tagline: string;
  icon: string;
  premise: string;
  partner?: boolean;
  seoSubject: string;
  sections: string[];
}

const SPECS: Spec[] = [
  {
    id: "brutal-blueprint",
    title: "THE BRUTAL BLUEPRINT™",
    tagline: "The astrology report that tells you what everyone else is too afraid to say.",
    icon: "☠",
    seoSubject: "personality, contradictions, blind spots and shadow patterns",
    premise:
      "Hold up an astrological mirror and describe what the chart may reveal about personality patterns, contradictions, blind spots, shadow tendencies, interpersonal impact, defenses, vulnerabilities and self-sabotage. Distinguish throughout between who the subject believes they are, who they present themselves as, and how their patterns may actually land on other people.",
    sections: [
      "Before We Get Brutal: How to Read This Report",
      "The Person You Think You Are",
      "The Person Other People Experience",
      "The Mask You Wear",
      "What You're Hiding From Yourself",
      "Your Psychological Pressure Points",
      "Your Darkest Personality Patterns",
      "The Shadow Self",
      "Your Favorite Defense Mechanisms",
      "How You Sabotage Yourself",
      "The Things You Do That Drive People Crazy",
      "Control, Power & Ego",
      "Jealousy, Possession & Insecurity",
      "Love: The Fantasy vs. The Reality",
      "How You Behave When You Want Someone",
      "How You Behave When You Stop Wanting Someone",
      "Conflict: Who You Become When You're Angry",
      "Communication: What You Say vs. What People Hear",
      "Your Relationship Red Flags",
      "Your Friendship Red Flags",
      "Your Accountability Problem",
      "The Contradictions in Your Personality",
      "The Lies You Might Tell Yourself",
      "What You Blame on Other People",
      "What Other People May Be Afraid to Tell You",
      "Your Greatest Strengths — Without the Flattery",
      "Where Your Darkness Becomes Power",
      "What Happens If You Never Change",
      "The Mature Version of You",
      "The Brutal Truths You Actually Need",
      "The Final Verdict: Your Cosmic Reality Check",
    ],
  },
  {
    id: "unspoken-contract",
    title: "THE UNSPOKEN CONTRACT™",
    tagline: "The brutally honest truth about how you actually love people.",
    icon: "⚭",
    seoSubject: "relationship terms, attachment, withdrawal and exit patterns",
    premise:
      "Expose the unwritten terms this person brings to intimacy: what they silently expect, what they withhold, what they punish, what they call a boundary that may be a wall, what they call loyalty that may be control. Cover pursuit, withdrawal, leverage, jealousy, conflict, apology, exit style and the recurring pattern they may blame on other people.",
    sections: [
      "Before We Get Brutal: How to Read This Report",
      "The Partner You Believe You Are",
      "The Partner Other People Actually Get",
      "The Terms You Never Say Out Loud",
      "What You Promise vs. What You Deliver",
      "What You Secretly Expect in Return",
      "Your Attachment Pattern, Without the Comfort",
      "The Type You Chase and Why It Keeps Costing You",
      "How You Behave in the First Three Weeks",
      "The Moment You Start Withdrawing",
      "Your Intimacy Ceiling",
      "How You Use Sex, Distance, or Attention as Leverage",
      "Jealousy, Comparison & Ownership",
      "The Fights You Start Without Admitting You Started Them",
      "Stonewalling, Scorekeeping & Silent Punishment",
      "How You Behave When You're the One Who Cares Less",
      "How You Behave When You're the One Who Cares More",
      "The Apologies You Give That Aren't Apologies",
      "What You Call Boundaries That May Be Walls",
      "What You Call Loyalty That May Be Control",
      "Your Exit Style: How You End Things",
      "The Stories You Tell About Your Exes",
      "Your Part in the Pattern You Keep Blaming Them For",
      "Friendship: The Same Contract, Different Signature",
      "Family: Where the Contract Was Written",
      "What Partners May Be Afraid to Tell You",
      "Your Real Relational Gifts — Without the Flattery",
      "Where Your Intensity Becomes Devotion",
      "What Happens If You Renegotiate Nothing",
      "The Brutal Truths You Actually Need",
      "The Final Verdict: The Contract You Choose Next",
    ],
  },
  {
    id: "ambition-autopsy",
    title: "THE AMBITION AUTOPSY™",
    tagline: "Why you haven't gotten where you said you'd be.",
    icon: "⚒",
    seoSubject: "ambition, discipline, money behavior and the gap between goals and output",
    premise:
      "Perform a post-mortem on the distance between what this person says they want and what their behavior actually produces. Name the quitting point, the avoidance dressed as standards, the procrastination dressed as preparation, the entitlement dressed as confidence, the money behavior dressed as principle, and the excuses that recur.",
    sections: [
      "Before We Get Brutal: How to Read This Report",
      "The Version of Success You Say You Want",
      "The Version Your Chart Is Actually Built For",
      "The Gap Between Stated Goals and Actual Behavior",
      "What You Actually Optimize For",
      "Your Relationship With Effort",
      "Perfectionism as a Socially Acceptable Defense",
      "Procrastination: What You're Really Avoiding",
      "The Point Where You Reliably Quit",
      "How You Sabotage Momentum Right Before It Pays",
      "Confidence vs. Entitlement",
      "Your Discipline Problem, Named Precisely",
      "How You Handle Being Outperformed",
      "Envy, Comparison & the Scoreboard You Won't Admit To",
      "Authority: How You React to Being Told What to Do",
      "Power: How You Behave When You Have It",
      "Money: Avoidance, Anxiety, or Identity",
      "What You Overspend On and What That Buys You Emotionally",
      "How You Talk About Money vs. How You Handle It",
      "Risk: Reckless, Frozen, or Selectively Brave",
      "The Excuses You Reuse",
      "What You Blame on Timing, Luck, or Other People",
      "Collaboration: Why Some People Stop Working With You",
      "The Feedback You Dismiss",
      "What Colleagues May Be Afraid to Tell You",
      "Your Real Working Genius — Without the Flattery",
      "Where Your Hunger Becomes Mastery",
      "What Happens If You Keep This Operating System",
      "The Mature Professional Version of You",
      "The Brutal Truths You Actually Need",
      "The Final Verdict: The Work You Owe Yourself",
    ],
  },
  {
    id: "self-sabotage-file",
    title: "THE SELF-SABOTAGE FILE™",
    tagline: "You already know what you're doing. This report explains why you keep doing it.",
    icon: "⚠",
    seoSubject: "self-sabotage, avoidance, perfectionism and repeating delay",
    premise:
      "Investigate the gap between what the person says they want and the patterns that repeatedly interfere with obtaining it. Treat self-sabotage as a pattern of competing drives rather than a moral defect.",
    sections: [
      "Before We Get Brutal: How to Read This File",
      "What You Say You Want",
      "What Your Behavior May Actually Be Protecting",
      "The Pattern Beneath the Pattern",
      "What You Do When Success Gets Too Close",
      "Your Psychological Pressure Points",
      "The Forms Your Avoidance Can Take",
      "The Shadow Saboteur",
      "Your Favorite Excuses",
      "How You Delay Your Own Life",
      "The Things You Keep Repeating",
      "Control, Fear & the Need to Know",
      "Perfectionism, Pride & the Fear of Failure",
      "Success: The Fantasy vs. the Responsibility",
      "What Happens When You Finally Want Something Badly",
      "What Happens When You Lose Interest",
      "Conflict With Yourself",
      "What You Tell Yourself vs. What Your Patterns Say",
      "Your Self-Sabotage Red Flags",
      "How Your Patterns Affect Other People",
      "Your Accountability Problem",
      "The Contradictions Driving the Cycle",
      "The Lies You May Tell Yourself",
      "What You Blame on Circumstances",
      "What Someone Who Loves You Might Tell You",
      "Your Strengths Without the Excuses",
      "Where Your Shadow Can Become Discipline",
      "What Happens If Nothing Changes",
      "The Version of You That Stops Fighting Yourself",
      "The Brutal Truths You Actually Need",
      "The Final File: What You Do Next",
    ],
  },
  {
    id: "mirror-you-avoid",
    title: "THE MIRROR YOU AVOID™",
    tagline: "The version of you that exists when nobody is watching.",
    icon: "◉",
    seoSubject: "self-image, persona, private identity and authenticity",
    premise:
      "Explore the difference between self-image, social presentation, private impulses, and the deeper identity reflected by the chart.",
    sections: [
      "Before We Get Honest: The Mirror",
      "The Person You Think You Are",
      "The Person You Perform",
      "The Person You Hide",
      "What You Need People to Believe",
      "Your Identity Pressure Points",
      "The Shadow Behind Your Image",
      "The Self You Don't Advertise",
      "Your Favorite Masks",
      "Where Image Becomes a Trap",
      "What You Fear Being Seen Doing",
      "Pride, Vulnerability & Exposure",
      "Insecurity Behind Confidence",
      "Authenticity: Fantasy vs. Reality",
      "Who You Become When Nobody Approves",
      "Who You Become When Nobody Is Watching",
      "The Identity You Defend",
      "What You Say About Yourself vs. What the Chart Suggests",
      "Your Image Red Flags",
      "How Others May Experience Your Persona",
      "The Accountability Gap",
      "The Contradictions Inside Your Identity",
      "The Stories You Tell Yourself",
      "What You Refuse to See",
      "What Honest People Might Tell You",
      "Your Real Strengths",
      "Where the Shadow Becomes Authentic Power",
      "What Happens If You Keep Performing",
      "The Self You Can Finally Own",
      "The Brutal Truths",
      "The Final Mirror",
    ],
  },
  {
    id: "shadow-ledger",
    title: "THE SHADOW LEDGER™",
    tagline: "Every strength has a bill. This report shows you the balance.",
    icon: "♇",
    seoSubject: "strengths, their hidden costs and the shadow side of talent",
    premise:
      "Every major strength carries a potential shadow cost. Identify the exchange rate: what this chart gives easily, what it makes expensive, and what overuse of each gift may cost in relationships, work and self-perception.",
    sections: [
      "Before We Begin: Reading the Ledger",
      "Your Most Obvious Strengths",
      "The Hidden Cost of Those Strengths",
      "What Your Chart Gives Easily",
      "What Your Chart Makes Expensive",
      "Your Pressure Points",
      "When Strength Becomes Shadow",
      "The Parts of Yourself You Overuse",
      "Your Favorite Forms of Control",
      "Where Competence Becomes Isolation",
      "Where Independence Becomes Distance",
      "Where Confidence Becomes Pride",
      "Where Sensitivity Becomes Defensiveness",
      "Power: The Price of Having It",
      "What You Do When You Feel Powerful",
      "What You Do When You Feel Powerless",
      "Conflict With Your Own Strength",
      "What You Call a Strength vs. What Others May Experience",
      "Your Shadow Red Flags",
      "The Cost to Relationships",
      "The Cost to Yourself",
      "Your Internal Contradictions",
      "The Rationalizations",
      "The Bill You Keep Avoiding",
      "What Someone Honest Would Charge You",
      "Your Strengths Without the Marketing",
      "Turning Shadow Into Mastery",
      "What Happens If You Refuse the Lesson",
      "The Integrated Version of You",
      "Five Brutal Truths",
      "The Final Balance",
    ],
  },
  {
    id: "inner-courtroom",
    title: "THE INNER COURTROOM™",
    tagline: "The prosecution has evidence. The defense has excuses. You get to hear both.",
    icon: "⚖",
    seoSubject: "self-accusation, defenses, excuses and accountability",
    premise:
      "Conduct a symbolic courtroom examination of competing parts of the personality: the case against, the case for, the evidence in the chart, the defenses, the cross-examination and a fairer internal standard. The courtroom is a metaphor — never imply actual legal wrongdoing.",
    sections: [
      "Court Is Now in Session",
      "The Case Against You",
      "The Case For You",
      "The Witness Called \u201cYour Chart\u201d",
      "Your Strongest Evidence",
      "Your Psychological Pressure Points",
      "The Pattern the Prosecution Keeps Returning To",
      "The Shadow Takes the Stand",
      "Your Favorite Defense",
      "The Excuses on Record",
      "The Habit That Keeps Getting You Recharged",
      "Control and Power Under Cross-Examination",
      "Jealousy, Pride and Fear",
      "The Story vs. The Evidence",
      "Your Behavior When You Want Something",
      "Your Behavior When You Don't Get It",
      "Conflict Under Oath",
      "Your Words vs. Your Pattern",
      "Red Flags Entered Into Evidence",
      "Witnesses: How Others May Experience You",
      "The Accountability Question",
      "Contradictions in the Record",
      "The Stories That Don't Survive Cross-Examination",
      "The Blame Game",
      "The Testimony You May Not Want to Hear",
      "Evidence of Your Better Nature",
      "The Shadow's Unexpected Value",
      "The Sentence If Nothing Changes",
      "The Case for Transformation",
      "Five Brutal Truths",
      "Verdict: What You Do With the Evidence",
    ],
  },
  {
    id: "pattern-that-wont-die",
    title: "THE PATTERN THAT WON'T DIE™",
    tagline: "Different people. Different circumstances. Same damn pattern.",
    icon: "⟳",
    seoSubject: "repeating emotional and behavioral cycles",
    premise:
      "Identify repeating behavioral and emotional signatures within the natal chart: where the cycle begins, what triggers it, why familiar pain feels safe, and how the loop can be interrupted and redesigned.",
    sections: [
      "Before We Start: Pattern Recognition",
      "The Pattern You Notice",
      "The Pattern You Don't",
      "Your Repetition Signature",
      "Where the Cycle Begins",
      "Your Trigger Points",
      "The Shadow Loop",
      "The Emotional Repeat Button",
      "Your Favorite Defense",
      "How You Recreate Familiar Problems",
      "What You Keep Choosing",
      "Control and Repetition",
      "Fear, Attachment and Familiar Pain",
      "The Fantasy of \u201cThis Time Will Be Different\u201d",
      "What You Do at the Beginning",
      "What You Do in the Middle",
      "What You Do Near the End",
      "What You Say vs. What Repeats",
      "The Red Flags You Keep Ignoring",
      "The People You May Keep Attracting",
      "Your Accountability Loop",
      "The Contradiction Keeping the Cycle Alive",
      "The Story That Protects the Pattern",
      "What You Blame",
      "The Truth Someone Close to You Might See",
      "What You Actually Do Well",
      "Breaking the Pattern Without Breaking Yourself",
      "What Repetition Costs",
      "The New Pattern",
      "Five Brutal Truths",
      "The Pattern Ends Here",
    ],
  },
  {
    id: "relationship-crime-scene",
    title: "THE RELATIONSHIP CRIME SCENE™",
    tagline: "Something happened between you. Your charts may explain what.",
    icon: "⚯",
    partner: true,
    seoSubject: "relationship dynamics, friction, triggers and repair potential",
    premise:
      "Conduct a forensic-style examination of the relationship dynamic between two charts. \u201cCrime scene\u201d is purely metaphorical and must never imply actual criminal conduct or wrongdoing by either person.",
    sections: [
      "Before We Enter the Scene",
      "Who You Are When You Meet Them",
      "Who They Are When They Meet You",
      "The First Point of Impact",
      "The Evidence Between Your Charts",
      "Your Psychological Pressure Points Together",
      "The Darkest Pattern You Activate",
      "The Shadow Relationship",
      "Your Favorite Defensive Moves",
      "How This Connection Can Sabotage You",
      "What Gets Under Your Skin",
      "Control, Power & Ego",
      "Jealousy, Possession & Insecurity",
      "Attraction: Fantasy vs. Reality",
      "Why You Want Each Other",
      "What Happens When One Pulls Away",
      "Conflict: Who You Become Together",
      "Communication: What You Say vs. What the Dynamic May Hear",
      "The Relationship Red Flags",
      "The Places You Trigger Each Other",
      "The Accountability Problem Between You",
      "The Contradictions in the Connection",
      "The Story You May Tell About This Relationship",
      "What the Charts Actually Support",
      "What Neither Person May Want to Admit",
      "What This Connection Does Well",
      "Where the Darkness Can Become Growth",
      "The Breaking Point",
      "The Repair Potential",
      "Five Brutal Truths About This Connection",
      "The Final Scene: What You Do With It",
    ],
  },
  {
    id: "chemistry-autopsy",
    title: "THE CHEMISTRY AUTOPSY™",
    tagline: "Why does this person get under your skin?",
    icon: "⚗",
    partner: true,
    seoSubject: "attraction, fascination, projection and emotional charge",
    premise:
      "Dissect attraction, fascination, emotional charge, friction and interpersonal activation between two charts — separating genuine chemistry from projection.",
    sections: [
      "Before We Dissect the Chemistry",
      "What You Bring Into the Connection",
      "What They Bring Into the Connection",
      "The First Spark",
      "The Astrological Evidence",
      "What Activates You",
      "What Activates Them",
      "The Shadow Chemistry",
      "Defensive Reactions",
      "Why You Can't Easily Ignore It",
      "The Irritation Factor",
      "Power and Magnetism",
      "Desire, Insecurity and Projection",
      "Attraction: Fantasy vs. Reality",
      "Pursuit",
      "Withdrawal",
      "Conflict Chemistry",
      "Communication Chemistry",
      "The Red Flags",
      "Emotional Triggers",
      "The Accountability Question",
      "The Contradiction",
      "The Story You May Be Telling Yourself",
      "What the Charts Actually Show",
      "What This Connection May Be Asking You to Confront",
      "The Chemistry That Helps You Grow",
      "Turning Intensity Into Consciousness",
      "When Chemistry Becomes Too Much",
      "Mature Attraction",
      "Five Brutal Truths",
      "The Final Autopsy",
    ],
  },
  {
    id: "power-struggle",
    title: "THE POWER STRUGGLE™",
    tagline: "Who pulls the strings—and what happens when neither of you lets go?",
    icon: "♜",
    partner: true,
    seoSubject: "control, autonomy, influence and authority between two people",
    premise:
      "Investigate control, autonomy, influence, authority, vulnerability, competition and mutual empowerment between two charts.",
    sections: [
      "Before the Power Game Begins",
      "Your Relationship With Power",
      "Their Relationship With Power",
      "Where the Charts Collide",
      "The Evidence of Influence",
      "Control Pressure Points",
      "The Shadow Power Dynamic",
      "Who Pushes and Who Pulls",
      "Defensive Control",
      "How the Dynamic Can Become Self-Sabotage",
      "Independence vs. Attachment",
      "Ego, Authority and Pride",
      "Possession and Insecurity",
      "Power: Fantasy vs. Reality",
      "Who Pursues",
      "Who Withdraws",
      "Who Escalates",
      "Who Feels Unheard",
      "Relationship Red Flags",
      "Trigger Points",
      "Mutual Accountability",
      "The Power Contradiction",
      "The Story Each Person May Tell",
      "What the Charts Actually Support",
      "The Conversation the Dynamic Demands",
      "Shared Power",
      "Turning Control Into Trust",
      "The Breaking Point",
      "The Mature Power Dynamic",
      "Five Brutal Truths",
      "Who Holds the Power When Nobody Has to",
    ],
  },
  {
    id: "unfinished-business",
    title: "THE UNFINISHED BUSINESS™",
    tagline: "Some connections feel bigger than the amount of time you've known each other.",
    icon: "∞",
    partner: true,
    seoSubject: "familiarity, intensity and unresolved relational themes",
    premise:
      "Explore recurring themes, emotional intensity, familiarity, unresolved tension and growth-oriented relationship symbolism between two charts. Never state that two people are cosmically destined to remain together; \u201ckarmic\u201d and \u201cfated\u201d language must be framed as astrological symbolism, never factual certainty.",
    sections: [
      "Before We Call It Fate",
      "What You Carry Into This Connection",
      "What They Carry Into It",
      "Why It Can Feel Familiar",
      "The Astrological Evidence",
      "The Pressure Points",
      "The Shadow Contract",
      "What Keeps Pulling You Back",
      "Your Defenses",
      "How the Connection Can Keep You Stuck",
      "The Pattern You Recognize",
      "Power, Attachment and Vulnerability",
      "Fear of Losing the Connection",
      "Fate vs. Projection",
      "What Draws You Toward Them",
      "What Makes You Step Away",
      "The Conflict Loop",
      "The Unspoken Conversation",
      "Red Flags",
      "Repeating Triggers",
      "The Accountability Problem",
      "The Contradiction",
      "The Story of \u201cMeant to Be\u201d",
      "What the Charts Actually Support",
      "What This Connection May Be Teaching",
      "The Gift Hidden Inside the Pattern",
      "Growth Without Romanticizing Pain",
      "What Happens If Nothing Changes",
      "Completion vs. Continuation",
      "Five Brutal Truths",
      "What \u201cUnfinished\u201d Really Means",
    ],
  },
  {
    id: "attraction-trap",
    title: "THE ATTRACTION TRAP™",
    tagline:
      "The person you can't stop wanting may be activating the exact thing you need to understand.",
    icon: "♥",
    partner: true,
    seoSubject: "desire, projection, idealization and conscious choice",
    premise:
      "Examine desire, projection, idealization, activation and discernment between two charts — what is chemistry, what is projection, and what the attraction may be asking the reader to understand.",
    sections: [
      "Before We Call It Attraction",
      "What You Want",
      "What They Activate",
      "The Astrological Spark",
      "The Evidence of Attraction",
      "Your Vulnerability Points",
      "The Shadow Attraction",
      "What Feels Irresistible",
      "What Feels Familiar",
      "Where Attraction Can Become Self-Sabotage",
      "Fantasy, Projection and Desire",
      "Power and Magnetism",
      "Jealousy and Insecurity",
      "Desire: Fantasy vs. Reality",
      "Pursuit",
      "Withdrawal",
      "Conflict After Attraction",
      "Communication Under Desire",
      "Attraction Red Flags",
      "Trigger Points",
      "Accountability",
      "The Contradiction",
      "The Story You May Be Telling Yourself",
      "What the Charts Actually Support",
      "The Question Attraction Is Asking",
      "The Healthy Version of the Chemistry",
      "Turning Desire Into Awareness",
      "When Attraction Becomes a Trap",
      "Conscious Choice",
      "Five Brutal Truths",
      "The Final Question: Do You Want Them—or What They Activate?",
    ],
  },
  {
    id: "things-we-wont-say",
    title: "THE THINGS WE WON'T SAY™",
    tagline: "The conversation happening underneath the conversation.",
    icon: "☿",
    partner: true,
    seoSubject: "communication, avoidance, silence and honest dialogue",
    premise:
      "Examine communication patterns, avoidance, indirect expression, vulnerability, assumptions and conversational tension between two charts.",
    sections: [
      "Before We Have the Conversation",
      "How You Communicate",
      "How They Communicate",
      "What Happens Between the Words",
      "The Astrological Evidence",
      "Communication Pressure Points",
      "The Shadow Conversation",
      "What Gets Avoided",
      "Your Favorite Defensive Responses",
      "How Silence Can Become a Weapon Against Yourself",
      "Misunderstanding",
      "Control and Communication",
      "Insecurity Behind the Words",
      "What You Say vs. What You Mean",
      "What Happens When You Want Something",
      "What Happens When You Are Hurt",
      "Conflict Language",
      "How the Other Person May Experience the Dynamic",
      "Communication Red Flags",
      "Trigger Words and Themes",
      "Accountability in Conversation",
      "Contradictions",
      "The Stories You May Tell Yourselves",
      "What the Charts Actually Support",
      "The Conversation You May Need",
      "What You Do Well Together",
      "Turning Silence Into Honesty",
      "What Happens If Nothing Gets Said",
      "The Mature Conversation",
      "Five Brutal Truths",
      "What Finally Needs to Be Said",
    ],
  },
  {
    id: "breaking-point",
    title: "THE BREAKING POINT™",
    tagline: "Every connection has a pressure limit. Find yours before you reach it.",
    icon: "◈",
    partner: true,
    seoSubject: "relational pressure, escalation, repair and resilience",
    premise:
      "Identify areas of maximum relational pressure between two charts without predicting an inevitable breakup or collapse. Emphasize the warning, the repair strengths and the choice available before the pressure peaks.",
    sections: [
      "Before We Find the Pressure Limit",
      "What You Can Tolerate",
      "What They Can Tolerate",
      "Where the Pressure Begins",
      "The Astrological Evidence",
      "Your Trigger Points",
      "The Shadow Under Stress",
      "How You Defend Yourself",
      "How They May Defend Themselves",
      "How the Dynamic Can Escalate",
      "Control and Resistance",
      "Ego and Pride",
      "Jealousy and Insecurity",
      "Stress: Fantasy vs. Reality",
      "What You Do When Things Are Good",
      "What You Do When Things Go Wrong",
      "Conflict at Maximum Pressure",
      "Communication at Maximum Pressure",
      "The Red Flags",
      "The Trigger Sequence",
      "Mutual Accountability",
      "The Contradiction",
      "The Story That Can Keep You Trapped",
      "What the Charts Actually Support",
      "The Warning the Dynamic Gives You",
      "Your Repair Strengths",
      "Turning Pressure Into Growth",
      "The Breaking Point",
      "What Prevents the Break",
      "Five Brutal Truths",
      "The Choice Before the Breaking Point",
    ],
  },
  {
    id: "identity-collapse",
    title: "THE IDENTITY COLLAPSE™",
    tagline: "What happens when the person you built isn't the person you're becoming?",
    icon: "◇",
    seoSubject: "identity transition, reinvention and outdated self-concepts",
    premise:
      "Explore identity transitions, outdated self-concepts, reinvention, grief and the tension between stability and evolution.",
    sections: [
      "Before the Old Identity Falls",
      "The Person You Built",
      "The Person You Are Becoming",
      "The Identity You Defend",
      "The Evidence in Your Chart",
      "Identity Pressure Points",
      "The Shadow of Reinvention",
      "What You Outgrow",
      "The Masks That No Longer Fit",
      "How You Can Resist Your Own Evolution",
      "Independence and Belonging",
      "Ego and Identity",
      "Fear of Being Misunderstood",
      "Reinvention: Fantasy vs. Reality",
      "Who You Become When You Are Free",
      "Who You Become When You Are Cornered",
      "Identity Conflict",
      "What You Say You Are vs. What You Are Becoming",
      "Identity Red Flags",
      "How Others May Experience Your Evolution",
      "Accountability",
      "Contradictions",
      "The Story You Need to Retire",
      "What You Blame for Staying Stuck",
      "What Honest People May See",
      "Your Authentic Strengths",
      "Where Collapse Becomes Transformation",
      "What Happens If You Refuse to Evolve",
      "The Integrated Identity",
      "Five Brutal Truths",
      "The New Self",
    ],
  },
  {
    id: "excuse-machine",
    title: "THE EXCUSE MACHINE™",
    tagline: "Your reasons may be real. They may also be protecting you.",
    icon: "⚙",
    seoSubject: "rationalization, blame, delay and avoidance",
    premise:
      "Investigate rationalization, avoidance, intellectualization, blame, delay and the stories used to justify inaction — and replace excuses with experiments.",
    sections: [
      "Before We Dismantle the Machine",
      "Your Favorite Reasons",
      "What Your Reasons Protect",
      "The Pattern Beneath the Excuse",
      "The Evidence",
      "Pressure Points",
      "Your Shadow Rationalizations",
      "The Stories You Tell Yourself",
      "Your Favorite Escape Routes",
      "How Excuses Become Habits",
      "What You Keep Postponing",
      "Control and Certainty",
      "Fear of Failure",
      "Responsibility: Fantasy vs. Reality",
      "What You Do When Opportunity Arrives",
      "What You Do When Opportunity Disappears",
      "Conflict With Responsibility",
      "Your Words vs. Your Behavior",
      "Excuse Red Flags",
      "How Others May Experience the Pattern",
      "Accountability",
      "Contradictions",
      "The Lie Inside the Truth",
      "Who You Blame",
      "What Someone Honest Would Say",
      "Your Actual Strengths",
      "Turning Reasons Into Action",
      "What the Machine Costs",
      "The Person Who No Longer Needs Excuses",
      "Five Brutal Truths",
      "Shut the Machine Down",
    ],
  },
  {
    id: "power-bill",
    title: "THE POWER BILL™",
    tagline: "You asked for power. Here's what it's going to cost you.",
    icon: "⚜",
    seoSubject: "ambition, authority, leadership and the cost of power",
    premise:
      "Examine ambition, influence, leadership, authority, responsibility, control and the real cost of becoming powerful.",
    sections: [
      "Before You Ask for More",
      "What Power Means to You",
      "What You Want Power to Give You",
      "Your Natural Authority",
      "The Astrological Evidence",
      "Power Pressure Points",
      "The Shadow of Authority",
      "Where You Overreach",
      "Where You Underuse Yourself",
      "How Power Can Become Self-Sabotage",
      "Control and Independence",
      "Ego and Recognition",
      "Status and Insecurity",
      "Power: Fantasy vs. Responsibility",
      "What You Do When You Win",
      "What You Do When You Lose",
      "Conflict Under Authority",
      "Communication From a Position of Power",
      "Leadership Red Flags",
      "How Others May Experience Your Authority",
      "Accountability",
      "Contradictions",
      "The Stories You Tell About Deserving Power",
      "What You Blame",
      "What Honest People May Tell You",
      "Your Strengths Without the Ego",
      "Where Shadow Becomes Leadership",
      "The Cost of Unintegrated Power",
      "Responsible Power",
      "Five Brutal Truths",
      "The Final Bill",
    ],
  },
  {
    id: "cosmic-cross-examination",
    title: "THE COSMIC CROSS-EXAMINATION™",
    tagline: "No flattering answers. No convenient witnesses. Just the chart.",
    icon: "⚔",
    seoSubject: "the complete unfiltered interrogation of a natal chart",
    premise:
      "This is the broadest interrogation-style natal report in the Unfiltered Series — the closest thing to an astrological \u201ctell me everything I don't want to hear\u201d experience. Cover identity, shadow, defenses, self-sabotage, love, anger, communication, accountability and self-deception at maximum candour, always evidence-bound.",
    sections: [
      "Court Is Open: How to Read This Examination",
      "The Identity You Present",
      "The Identity Others May Experience",
      "The Mask",
      "The Evidence You Avoid",
      "Your Pressure Points",
      "Your Darkest Patterns",
      "Your Shadow",
      "Your Favorite Defenses",
      "Self-Sabotage",
      "What Makes Other People Struggle With You",
      "Control and Power",
      "Jealousy, Pride and Insecurity",
      "Love: Fantasy vs. Reality",
      "Desire and Pursuit",
      "Withdrawal and Detachment",
      "Anger and Conflict",
      "Communication Under Cross-Examination",
      "Relationship Red Flags",
      "Friendship and Social Red Flags",
      "Accountability",
      "Contradictions",
      "Self-Deception",
      "Blame",
      "The Testimony You May Not Want",
      "Strengths Without Flattery",
      "Shadow as Power",
      "The Consequences of Refusal",
      "The Mature Version",
      "Five Brutal Truths",
      "Final Cross-Examination",
    ],
  },
  {
    id: "final-mirror",
    title: "THE FINAL MIRROR™",
    tagline: "You can close the report. You can't unsee yourself.",
    icon: "◎",
    seoSubject: "self-recognition, integration and personal transformation",
    premise:
      "This is the culmination report of the Unfiltered Series, focused on self-recognition, integration, accountability and transformation. Be honest about what makes this person difficult and equally precise about what makes them worth knowing.",
    sections: [
      "Before You Look",
      "The Person You Think You Are",
      "The Person the Chart Reflects",
      "The Mask",
      "The Truth Beneath It",
      "Your Pressure Points",
      "Your Shadow",
      "Your Defenses",
      "Your Self-Sabotage",
      "Your Repeating Patterns",
      "What Makes You Difficult to Love",
      "What Makes You Worth Knowing",
      "Fear, Pride and Insecurity",
      "Love: Fantasy vs. Reality",
      "Desire",
      "Detachment",
      "Conflict",
      "Communication",
      "Relationship Red Flags",
      "Social Red Flags",
      "Accountability",
      "Contradictions",
      "Self-Deception",
      "Blame",
      "What You Need to Hear",
      "Your Strengths Without the Flattery",
      "Your Shadow as Power",
      "The Cost of Remaining Unchanged",
      "The Person You Can Become",
      "Five Brutal Truths",
      "The Final Mirror",
    ],
  },
];

export const UNFILTERED_SERIES_REPORTS: ReportDefinition[] = SPECS.map((spec) => ({
  id: spec.id,
  title: spec.title,
  tagline: spec.tagline,
  icon: spec.icon,
  category: UNFILTERED_SERIES_CATEGORY,
  adult: false,
  sections: spec.sections,
  targetWords: UNFILTERED_SERIES_TARGET_WORDS,
  systemFraming: spec.partner
    ? SYNASTRY_FRAMING(spec.premise)
    : NATAL_FRAMING(spec.premise),
  requiresPartner: !!spec.partner,
  seoTitle: `${spec.title} | Brutally Honest Astrology Report | Cosmic Blueprint`,
  seoDescription: `A brutally honest astrology report exploring ${spec.seoSubject} through your ${
    spec.partner ? "synastry" : "natal"
  } chart. Discover patterns, contradictions, blind spots, strengths, and the truth you may be avoiding.`,
  estimatedPages: 35,
  readingMinutes: 25,
  difficulty: "Masterwork",
}));
